/// Maps every exercise name in the Gym Workout logging autocomplete list
/// (exerciseSuggestions) to one of the muscle groups used by the
/// recommendation engine (Chest, Back, Shoulders, Arms, Legs, Core).
///
/// WHY THIS EXISTS: Exercise.muscleGroup only had entries for the ~10
/// exercises in exercise_database.dart (my curated recommendation seed
/// list). But users log workouts by picking from a much larger ~250-item
/// autocomplete list - so ExerciseHistoryAnalyzer was failing to recognise
/// almost everything a real user actually logs, falling back to "unknown"
/// far more often than it should. This map fixes that by covering the
/// real list directly.
///
/// VOCABULARY MAPPING: the source list uses finer categories (Biceps,
/// Triceps, Quads, Hamstrings, Glutes, Calves, Forearms/Grip) than the
/// engine's 6 buckets, collapsed as follows:
///   Biceps, Triceps, Forearms/Grip  -> Arms
///   Quads, Hamstrings, Glutes, Calves -> Legs
///   Abs/Core -> Core
///
/// KEYS ARE LOWERCASE - matched against trimmed, lowercased logged names,
/// consistent with ExerciseHistoryAnalyzer's existing matching approach.
/// Apostrophes preserved exactly as they appear in the source list
/// (curly '’' in "Farmer's Carry" entries) since matching is exact-text.
const Map<String, String> kExerciseMuscleGroupMap = {
  // Chest
  'bench press': 'Chest',
  'barbell bench press': 'Chest',
  'dumbbell bench press': 'Chest',
  'smith machine bench press': 'Chest',
  'incline bench press': 'Chest',
  'incline barbell bench press': 'Chest',
  'incline dumbbell bench press': 'Chest',
  'incline smith machine bench press': 'Chest',
  'decline bench press': 'Chest',
  'decline barbell bench press': 'Chest',
  'decline dumbbell bench press': 'Chest',
  'close grip bench press': 'Chest',
  'machine chest press': 'Chest',
  'seated chest press': 'Chest',
  'incline machine chest press': 'Chest',
  'decline machine chest press': 'Chest',
  'plate loaded chest press': 'Chest',
  'single arm chest press': 'Chest',
  'cable chest press': 'Chest',
  'dumbbell floor press': 'Chest',
  'barbell floor press': 'Chest',
  'pec deck fly': 'Chest',
  'machine chest fly': 'Chest',
  'cable chest fly': 'Chest',
  'high cable fly': 'Chest',
  'low cable fly': 'Chest',
  'standing cable fly': 'Chest',
  'dumbbell fly': 'Chest',
  'incline dumbbell fly': 'Chest',
  'decline dumbbell fly': 'Chest',
  'dumbbell pullover': 'Chest',
  'cable pullover': 'Chest',
  'landmine chest press': 'Chest',

  // Back
  'lat pulldown': 'Back',
  'wide grip lat pulldown': 'Back',
  'close grip lat pulldown': 'Back',
  'neutral grip lat pulldown': 'Back',
  'reverse grip lat pulldown': 'Back',
  'single arm lat pulldown': 'Back',
  'straight arm pulldown': 'Back',
  'rope straight arm pulldown': 'Back',
  'seated cable row': 'Back',
  'close grip seated cable row': 'Back',
  'wide grip seated cable row': 'Back',
  'single arm cable row': 'Back',
  'barbell row': 'Back',
  'bent over barbell row': 'Back',
  'underhand barbell row': 'Back',
  'pendlay row': 'Back',
  'dumbbell row': 'Back',
  'single arm dumbbell row': 'Back',
  'chest supported dumbbell row': 'Back',
  'incline dumbbell row': 'Back',
  'machine row': 'Back',
  'seated machine row': 'Back',
  'plate loaded row': 'Back',
  'high row machine': 'Back',
  'low row machine': 'Back',
  't-bar row': 'Back',
  'landmine row': 'Back',
  'smith machine row': 'Back',
  'cable high row': 'Back',
  'deadlift': 'Back',
  'conventional deadlift': 'Back',
  'sumo deadlift': 'Legs', // posterior-chain/glute dominant - see note above
  'rack pull': 'Back',
  'back extension machine': 'Back',
  'weighted back extension': 'Back',

  // Shoulders
  'shoulder press': 'Shoulders',
  'barbell shoulder press': 'Shoulders',
  'dumbbell shoulder press': 'Shoulders',
  'seated dumbbell shoulder press': 'Shoulders',
  'standing dumbbell shoulder press': 'Shoulders',
  'machine shoulder press': 'Shoulders',
  'smith machine shoulder press': 'Shoulders',
  'overhead press': 'Shoulders',
  'military press': 'Shoulders',
  'arnold press': 'Shoulders',
  'landmine press': 'Shoulders',
  'single arm landmine press': 'Shoulders',
  'lateral raise': 'Shoulders',
  'dumbbell lateral raise': 'Shoulders',
  'cable lateral raise': 'Shoulders',
  'machine lateral raise': 'Shoulders',
  'single arm cable lateral raise': 'Shoulders',
  'leaning cable lateral raise': 'Shoulders',
  'front raise': 'Shoulders',
  'dumbbell front raise': 'Shoulders',
  'cable front raise': 'Shoulders',
  'plate front raise': 'Shoulders',
  'barbell front raise': 'Shoulders',
  'rear delt fly': 'Shoulders',
  'dumbbell rear delt fly': 'Shoulders',
  'cable rear delt fly': 'Shoulders',
  'machine rear delt fly': 'Shoulders',
  'reverse pec deck fly': 'Shoulders',
  'face pull': 'Shoulders',
  'upright row': 'Shoulders',
  'barbell upright row': 'Shoulders',
  'cable upright row': 'Shoulders',
  'dumbbell upright row': 'Shoulders',
  'shrugs': 'Shoulders',
  'dumbbell shrugs': 'Shoulders',
  'barbell shrugs': 'Shoulders',
  'smith machine shrugs': 'Shoulders',
  'cable shrugs': 'Shoulders',

  // Biceps -> Arms
  'biceps curl': 'Arms',
  'dumbbell curl': 'Arms',
  'barbell curl': 'Arms',
  'ez bar curl': 'Arms',
  'cable curl': 'Arms',
  'straight bar cable curl': 'Arms',
  'rope cable curl': 'Arms',
  'single arm cable curl': 'Arms',
  'alternating dumbbell curl': 'Arms',
  'seated dumbbell curl': 'Arms',
  'incline dumbbell curl': 'Arms',
  'hammer curl': 'Arms',
  'dumbbell hammer curl': 'Arms',
  'cable hammer curl': 'Arms',
  'rope hammer curl': 'Arms',
  'cross body hammer curl': 'Arms',
  'preacher curl': 'Arms',
  'ez bar preacher curl': 'Arms',
  'dumbbell preacher curl': 'Arms',
  'machine preacher curl': 'Arms',
  'spider curl': 'Arms',
  'concentration curl': 'Arms',
  'reverse curl': 'Arms',
  'ez bar reverse curl': 'Arms',
  'cable reverse curl': 'Arms',
  'zottman curl': 'Arms',
  'drag curl': 'Arms',
  'bayesian cable curl': 'Arms',

  // Triceps -> Arms
  'triceps pushdown': 'Arms',
  'rope pushdown': 'Arms',
  'straight bar pushdown': 'Arms',
  'v bar pushdown': 'Arms',
  'reverse grip pushdown': 'Arms',
  'cable triceps extension': 'Arms',
  'overhead triceps extension': 'Arms',
  'rope overhead triceps extension': 'Arms',
  'dumbbell overhead triceps extension': 'Arms',
  'single arm overhead triceps extension': 'Arms',
  'ez bar skull crusher': 'Arms',
  'dumbbell skull crusher': 'Arms',
  'cable skull crusher': 'Arms',
  'lying triceps extension': 'Arms',
  'incline triceps extension': 'Arms',
  'triceps kickback': 'Arms',
  'dumbbell triceps kickback': 'Arms',
  'cable triceps kickback': 'Arms',
  'machine triceps extension': 'Arms',
  'machine dip press': 'Arms',
  'jm press': 'Arms',

  // Quads -> Legs
  'squat': 'Legs',
  'barbell squat': 'Legs',
  'back squat': 'Legs',
  'front squat': 'Legs',
  'smith machine squat': 'Legs',
  'goblet squat': 'Legs',
  'dumbbell squat': 'Legs',
  'hack squat': 'Legs',
  'machine hack squat': 'Legs',
  'leg press': 'Legs',
  '45 degree leg press': 'Legs',
  'horizontal leg press': 'Legs',
  'single leg press': 'Legs',
  'narrow stance leg press': 'Legs',
  'wide stance leg press': 'Legs',
  'leg extension': 'Legs',
  'single leg extension': 'Legs',
  'lunges': 'Legs',
  'dumbbell lunges': 'Legs',
  'barbell lunges': 'Legs',
  'walking lunges': 'Legs',
  'reverse lunges': 'Legs',
  'smith machine lunges': 'Legs',
  'bulgarian split squat': 'Legs',
  'dumbbell bulgarian split squat': 'Legs',
  'smith machine bulgarian split squat': 'Legs',
  'split squat': 'Legs',
  'step up': 'Legs',
  'dumbbell step up': 'Legs',
  'belt squat': 'Legs',
  'landmine squat': 'Legs',
  'cyclist squat': 'Legs',

  // Hamstrings -> Legs
  'romanian deadlift': 'Legs',
  'barbell romanian deadlift': 'Legs',
  'dumbbell romanian deadlift': 'Legs',
  'smith machine romanian deadlift': 'Legs',
  'single leg romanian deadlift': 'Legs',
  'stiff leg deadlift': 'Legs',
  'dumbbell stiff leg deadlift': 'Legs',
  'good morning': 'Legs',
  'seated leg curl': 'Legs',
  'lying leg curl': 'Legs',
  'standing leg curl': 'Legs',
  'single leg curl': 'Legs',
  'cable hamstring curl': 'Legs',
  'glute ham raise machine': 'Legs',

  // Glutes -> Legs
  'hip thrust': 'Legs',
  'barbell hip thrust': 'Legs',
  'dumbbell hip thrust': 'Legs',
  'smith machine hip thrust': 'Legs',
  'machine hip thrust': 'Legs',
  'glute bridge': 'Legs',
  'barbell glute bridge': 'Legs',
  'dumbbell glute bridge': 'Legs',
  'cable glute kickback': 'Legs',
  'machine glute kickback': 'Legs',
  'cable pull through': 'Legs',
  'hip abduction': 'Legs',
  'seated hip abduction': 'Legs',
  'cable hip abduction': 'Legs',
  'machine hip abduction': 'Legs',
  'hip adduction': 'Legs',
  'seated hip adduction': 'Legs',
  'cable hip adduction': 'Legs',
  'sumo squat': 'Legs',
  'dumbbell sumo squat': 'Legs',

  // Calves -> Legs
  'standing calf raise': 'Legs',
  'seated calf raise': 'Legs',
  'machine calf raise': 'Legs',
  'smith machine calf raise': 'Legs',
  'leg press calf raise': 'Legs',
  'single leg calf raise': 'Legs',
  'dumbbell calf raise': 'Legs',
  'donkey calf raise': 'Legs',
  'calf press': 'Legs',
  'tibialis raise': 'Legs',
  'toe raise': 'Legs',

  // Abs / Core -> Core
  'cable crunch': 'Core',
  'machine crunch': 'Core',
  'weighted crunch': 'Core',
  'decline weighted crunch': 'Core',
  'weighted sit up': 'Core',
  'ab crunch machine': 'Core',
  'ab coaster': 'Core',
  'ab wheel rollout': 'Core',
  'barbell rollout': 'Core',
  'cable woodchop': 'Core',
  'high to low cable woodchop': 'Core',
  'low to high cable woodchop': 'Core',
  'pallof press': 'Core',
  'cable russian twist': 'Core',
  'weighted russian twist': 'Core',
  'medicine ball slam': 'Core',
  'medicine ball crunch': 'Core',

  // Forearms / Grip -> Arms
  'wrist curl': 'Arms',
  'barbell wrist curl': 'Arms',
  'dumbbell wrist curl': 'Arms',
  'cable wrist curl': 'Arms',
  'reverse wrist curl': 'Arms',
  'barbell reverse wrist curl': 'Arms',
  'dumbbell reverse wrist curl': 'Arms',
  'wrist roller': 'Arms',
  'farmer’s carry': 'Arms',
  'dumbbell farmer’s carry': 'Arms',
  'trap bar farmer’s carry': 'Arms',
  'plate pinch': 'Arms',
};
