// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN7lJZ23aQi6dyFVrD5nkx7pjEo4F5rYU',
    appId: '1:968571437373:web:34405ada04554a35be0554',
    messagingSenderId: '968571437373',
    projectId: 'fitza-cc47e',
    authDomain: 'fitza-cc47e.firebaseapp.com',
    storageBucket: 'fitza-cc47e.firebasestorage.app',
    measurementId: 'G-HV61LVS347',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx9ZcftRwUGS2ivYQJ7dwcFPON9tp2yc4',
    appId: '1:968571437373:android:462910c98c406a2bbe0554',
    messagingSenderId: '968571437373',
    projectId: 'fitza-cc47e',
    storageBucket: 'fitza-cc47e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbF_UVvnpwEUMxVvNX79tar2Yd_ao0Cyo',
    appId: '1:968571437373:ios:9071601b5f5f8ed5be0554',
    messagingSenderId: '968571437373',
    projectId: 'fitza-cc47e',
    storageBucket: 'fitza-cc47e.firebasestorage.app',
    iosBundleId: 'com.example.fitza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbF_UVvnpwEUMxVvNX79tar2Yd_ao0Cyo',
    appId: '1:968571437373:ios:9071601b5f5f8ed5be0554',
    messagingSenderId: '968571437373',
    projectId: 'fitza-cc47e',
    storageBucket: 'fitza-cc47e.firebasestorage.app',
    iosBundleId: 'com.example.fitza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN7lJZ23aQi6dyFVrD5nkx7pjEo4F5rYU',
    appId: '1:968571437373:web:81624cbb399d4aaebe0554',
    messagingSenderId: '968571437373',
    projectId: 'fitza-cc47e',
    authDomain: 'fitza-cc47e.firebaseapp.com',
    storageBucket: 'fitza-cc47e.firebasestorage.app',
    measurementId: 'G-4JEJ9KSDQY',
  );
}
